module.exports = {
    rules: {
        'arrow-body-style': 0,
        'arrow-parens': 2,
        'arrow-spacing': 2,
        'constructor-super': 2,
        'generator-star-spacing': 2,
        'no-class-assign': 2,
        'no-confusing-arrow': 0,
        'no-const-assign': 2,
        'no-dupe-class-members': 2,
        'no-duplicate-imports': 0,
        'no-new-symbol': 0,
        'no-restricted-imports': 0,
        'no-this-before-super': 2,
        'no-useless-computed-key': 0,
        'no-useless-constructor': 0,
        'no-useless-rename': 0,
        'no-var': 2,
        'object-shorthand': 2,
        'prefer-arrow-callback': 1,
        'prefer-const': 2,
        'prefer-numeric-literals': 0,
        'prefer-rest-params': 0,
        'prefer-spread': 2,
        'prefer-template': 1,
        'require-yield': 2,
        'rest-spread-spacing': 0,
        'sort-imports': 0,
        'symbol-description': 0,
        'template-curly-spacing': 0,
        'yield-star-spacing': 0
    }
};
