module.exports = {
    env: {
        browser: true,
        node: true
    },
    rules: {
        'array-bracket-spacing': [2, 'never'],
        // 'block-spacing': 2,
        'brace-style': 2,
        camelcase: 2,
        // NO_RULE 'capitalized-comments': 2,
        'comma-dangle': [2, 'never'],
        // 'comma-spacing': [ 2, { before: false, after: true } ],
        'comma-style': [2, 'last'],
        // 'computed-property-spacing': [ 2, 'never' ],
        // NO_RULE 'consistent-this': 2,
        'eol-last': 2,
        // 'func-call-spacing': [ 2, 'never' ],
        // 'func-name-matching': 2,
        // 'func-names': 2,
        'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
        // 'id-blacklist': 2,
        // NO_RULE 'id-length': 2,
        // 'id-match': [ 2, '^\\$?(__)?(([A-Z]|[a-z]|[0-9]+)|([A-Z_]))*\\$?$' ],
        indent: [2, 4, { SwitchCase: 1 }],
        // 'jsx-quotes': [ 2, 'prefer-double' ],
        'key-spacing': [2, { afterColon: true }],
        'keyword-spacing': [2, {}],
        // NO_RULE 'line-comment-position': 2,
        // 'linebreak-style': [ 2, 'unix' ],
        // NO_RULE 'lines-around-comment': 2,
        // NO_RULE 'lines-around-directive': 2,
        'max-depth': ['error', 2],
        'max-len': [2, 110],
        // 'max-lines': [ 2, { max: 500, skipBlankLines: false, skipComments: false } ],
        'max-nested-callbacks': ['error', 3],
        'max-params': ['error', 10],
        // 'max-statements-per-line': [ 2, { max: 1 } ],
        'max-statements': ['error', 20],
        // NO_RULE 'multiline-ternary': 2,
        'new-cap': 2,
        // 'new-parens': 2,
        'newline-after-var': [2, 'always'],
        // NO_RULE 'newline-before-return': 2,
        // NO_RULE 'newline-per-chained-call': 2,
        // 'no-array-constructor': 2,
        'no-bitwise': 2,
        // 'no-continue': 2,
        // NO_RULE 'no-inline-comments': 2,
        // 'no-lonely-if': 2,
        // NO_RULE 'no-mixed-operators': 2,
        'no-mixed-spaces-and-tabs': 2,
        'no-multiple-empty-lines': [2, { max: 1, maxEOF: 1 }],
        // 'no-negated-condition': 2,
        // 'no-nested-ternary': 2,
        // 'no-new-object': 2,
        // NO_RULE 'no-plusplus': 2,
        // NO_RULE 'no-restricted-syntax': 2,
        // 'no-tabs': 2,
        // NO_RULE 'no-ternary': 2,
        'no-trailing-spaces': 2,
        'no-underscore-dangle': 2,
        // 'no-unneeded-ternary': 2,
        // 'no-whitespace-before-property': 2,
        // NO_RULE 'object-curly-newline': 2,
        // NO_RULE 'object-curly-spacing': 2,
        // NO_RULE 'object-property-newline': 2,
        // 'one-var-declaration-per-line': 2,
        'one-var': [2, 'always'],
        // NO_RULE 'operator-assignment': 2,
        // 'operator-linebreak': [ 2, 'after' ],
        // NO_RULE 'padded-blocks': 2,
        // 'quote-props': [ 2, 'as-needed' ],
        quotes: [2, 'single'],
        // NO_RULE 'require-jsdoc': 2,
        // 'semi-spacing': [ 2, { before: false, after: true } ],
        semi: 2,
        // NO_RULE 'sort-keys': 2,
        // NO_RULE 'sort-vars': 2,
        'space-before-blocks': [2, 'always'],
        'space-before-function-paren': [2, 'always'],
        'space-in-parens': [2, 'never'],
        'space-infix-ops': 2,
        'space-unary-ops': [2, { words: false, nonwords: false }]
        // NO_RULE 'spaced-comment': 2,
        // 'unicode-bom': [ 2, 'never' ],
        // NO_RULE 'wrap-regex': 2
    }
};
